export const cnc_fields = [{
  coltype: 'string',
  prop: 'gcdm',
  label: '工厂',
  headeralign: 'center',
  align: 'center',
  width: 80,
}, {
  coltype: 'string',
  prop: 'scx',
  label: '生产线',
  headeralign: 'center',
  align: 'center',
  width: 80,
}, {
  coltype: 'string',
  prop: 'sbbh',
  label: '设备编号',
  headeralign: 'center',
  align: 'center',
  width: 100,
}, {
  coltype: 'string',
  prop: 'sbmc',
  label: '设备名称',
  headeralign: 'center',
  align: 'center',
  width: 100,
  overflowtooltip: true
},
{
  coltype: 'string',
  prop: 'gwh',
  label: '岗位号',
  headeralign: 'center',
  align: 'center',
  width: 80,
},
{
  coltype: 'string',
  prop: 'jgs',
  label: '加工数',
  headeralign: 'center',
  align: 'center',
  width: 80,
},
{
  coltype: 'string',
  prop: 'yxzt',
  label: '运行状态',
  headeralign: 'center',
  align: 'center',
  width: 80,
},
{
  coltype: 'string',
  prop: 'xhsj',
  label: '循环时间',
  headeralign: 'center',
  align: 'center',
  width: 80,
},
{
  coltype: 'string',
  prop: 'qxsj',
  label: '切削时间',
  headeralign: 'center',
  align: 'center',
  width: 80,
},
{
  coltype: 'string',
  prop: 'czsj',
  label: '操作时间',
  headeralign: 'center',
  align: 'center',
  width: 80,
},
{
  coltype: 'string',
  prop: 'kjsj',
  label: '开机时间',
  headeralign: 'center',
  align: 'center',
  width: 80,
},
{
  coltype: 'string',
  prop: 'yxsj',
  label: '运行时间',
  headeralign: 'center',
  align: 'center',
  width: 80,
},
{
  coltype: 'string',
  prop: 'jp',
  label: '节拍',
  headeralign: 'center',
  align: 'center',
  width: 80,
},
{
  coltype: 'string',
  prop: 'jjsd',
  label: '进给速度',
  headeralign: 'center',
  align: 'center',
  width: 80,
},
{
  coltype: 'string',
  prop: 'zzzs',
  label: '主轴转速',
  headeralign: 'center',
  align: 'center',
  width: 80,
},
{
  coltype: 'datetime',
  prop: 'lrsj',
  label: '采集时间',
  headeralign: 'center',
  align: 'center',
  width: 140,
  overflowtooltip: true
},
{
  coltype: 'string',
  prop: 'zzdjbh',
  label: '主轴刀具编号',
  headeralign: 'center',
  align: 'center',
  width: 80,
},
{
  coltype: 'string',
  prop: 'xybdjbh',
  label: '下一把刀具编号',
  headeralign: 'center',
  align: 'center',
  width: 80,
},
{
  coltype: 'string',
  prop: 'ksjjbl',
  label: '快速进给倍率',
  headeralign: 'center',
  align: 'center',
  width: 80,
},
{
  coltype: 'string',
  prop: 'jjsdccbl',
  label: '进给速度超程倍率',
  headeralign: 'center',
  align: 'center',
  width: 80,
},
{
  coltype: 'string',
  prop: 'zzbl',
  label: '主轴倍率',
  headeralign: 'center',
  align: 'center',
  width: 80,
},
{
  coltype: 'string',
  prop: 'dqcxm',
  label: '当前程序名',
  headeralign: 'center',
  align: 'center',
  width: 80,
},
{
  coltype: 'string',
  prop: 'zzfz',
  label: '主轴负载',
  headeralign: 'center',
  align: 'center',
  width: 80,
},
{
  coltype: 'string',
  prop: 'cffz1',
  label: '伺服负载1',
  headeralign: 'center',
  align: 'center',
  width: 80,
},
{
  coltype: 'string',
  prop: 'cffz2',
  label: '伺服负载2',
  headeralign: 'center',
  align: 'center',
  width: 80,
},
{
  coltype: 'string',
  prop: 'cffz3',
  label: '伺服负载3',
  headeralign: 'center',
  align: 'center',
  width: 80,
},
{
  coltype: 'string',
  prop: 'cffz4',
  label: '伺服负载4',
  headeralign: 'center',
  align: 'center',
  width: 80,
},
];
