export const gj_fields = [
{
    coltype: 'string',
    prop: 'gcdm',
    label: '工厂',
    headeralign: 'center',
    align: 'center',
    width: 80,
  }, {
    coltype: 'string',
    prop: 'scx',
    label: '生产线',
    headeralign: 'center',
    align: 'center',
    width: 80,
  }, {
    coltype: 'string',
    prop: 'sbbh',
    label: '设备编号',
    headeralign: 'center',
    align: 'center',
    width: 100,
  }, {
    coltype: 'string',
    prop: 'sbmc',
    label: '设备名称',
    headeralign: 'center',
    align: 'center',
    width:100,
	overflowtooltip: true
  },
  {
    coltype: 'string',
    prop: 'gwh',
    label: '岗位号',
    headeralign: 'center',
    align: 'center',
    width: 80,
  },
  {
    coltype: 'string',
    prop: 'kjzt',
    label: '开机状态',
    headeralign: 'center',
    align: 'center',
    width: 80,
  },
  {
    coltype: 'string',
    prop: 'yxzt',
    label: '运行状态',
    headeralign: 'center',
    align: 'center',
    width: 80,
  },
  {
    coltype: 'string',
    prop: 'bjzt',
    label: '报警状态',
    headeralign: 'center',
    align: 'center',
    width: 80,
  },
  {
    coltype: 'datetime',
    prop: 'lrsj',
    label: '采集时间',
    headeralign: 'center',
    align: 'center',
    width: 140,
    fixed: 'left',
	overflowtooltip: true
  },
];