export const hg_fields = [
{
    coltype: 'string',
    prop: 'gcdm',
    label: '工厂',
    headeralign: 'center',
    align: 'center',
    width: 80,
  }, {
    coltype: 'string',
    prop: 'scx',
    label: '生产线',
    headeralign: 'center',
    align: 'center',
    width: 80,
  }, {
    coltype: 'string',
    prop: 'sbbh',
    label: '设备编号',
    headeralign: 'center',
    align: 'center',
    width: 100,
  }, {
    coltype: 'string',
    prop: 'sbmc',
    label: '设备名称',
    headeralign: 'center',
    align: 'center',
    width:100,
	overflowtooltip: true
  },
  {
    coltype: 'string',
    prop: 'gwh',
    label: '岗位号',
    headeralign: 'center',
    align: 'center',
    width: 80,
  },
  {
    coltype: 'string',
    prop: 'jgs',
    label: '加工数',
    headeralign: 'center',
    align: 'center',
    width: 80,
  },
  {
    coltype: 'string',
    prop: 'yzzt',
    label: '运行状态',
    headeralign: 'center',
    align: 'center',
    width: 80,
  },
  {
    coltype: 'string',
    prop: 'wd',
    label: '温度',
    headeralign: 'center',
    align: 'center',
    width: 80,
  },
  {
    coltype: 'datetime',
    prop: 'lrsj',
    label: '采集时间',
    headeralign: 'center',
    align: 'center',
    width: 140,
	overflowtooltip: true
  },
];