export const spc_hj_fields = [
    {
        coltype: 'string',
        prop: 'gcdm',
        label: '工厂',
        headeralign: 'center',
        align: 'center',
        width: 80,
        fixed: 'left',
    }, {
        coltype: 'string',
        prop: 'scx',
        label: '生产线',
        headeralign: 'center',
        align: 'center',
        width: 80,
        fixed: 'left',
    }, {
        coltype: 'string',
        prop: 'sbbh',
        label: '设备编号',
        headeralign: 'center',
        align: 'center',
        width: 100,
        fixed: 'left',
    }, {
        coltype: 'string',
        prop: 'sbmc',
        label: '设备名称',
        headeralign: 'center',
        align: 'center',
        fixed: 'left',
        overflowtooltip: true
    },
    {
        coltype: 'string',
        prop: 'gwh',
        label: '岗位号',
        headeralign: 'center',
        align: 'center',
        width: 80,
        fixed: 'left',
    },
    {
        coltype: 'string',
        prop: 'wd',
        label: '温度',
        headeralign: 'center',
        align: 'center',
        width: 80,
        fixed: 'left',
    },
    {
        coltype: 'string',
        prop: 'sd',
        label: '湿度',
        headeralign: 'center',
        align: 'center',
        width: 80,
        fixed: 'left',
    },
    {
        coltype: 'datetime',
        prop: 'lrsj',
        label: '采集时间',
        headeralign: 'center',
        align: 'center',
        width: 140,
        fixed: 'left',
        overflowtooltip: true
    },
];